import { useEffect } from 'react'
import { prices, reviewThemes, services, site } from '../content/site'

export function HomePage() {
  useEffect(() => { const id = window.location.hash.slice(1); if (!id) return; const frame = window.requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView()); return () => window.cancelAnimationFrame(frame) }, [])
  return <>
    <section className="hero" id="top"><img className="hero-image" src={`${import.meta.env.BASE_URL}${site.heroImage}`} alt="Интерьер салона Мокко" /><div className="hero-overlay" /><div className="hero-copy"><p className="eyebrow">Владимир · Лермонтова, 21Б</p><h1>{site.tagline}</h1><p className="lede">{site.description}</p><div className="hero-actions"><a className="button button-accent" href={site.bookingUrl} target="_blank" rel="noreferrer">Выбрать время <span aria-hidden="true">↗</span></a><a className="button button-light" href="#services">Посмотреть услуги</a></div></div><div className="hero-facts"><p><strong>{site.trust.rating}</strong><span>рейтинг</span></p><p><strong>{site.trust.reviews}</strong><span>на Яндекс Картах</span></p><p><strong>09:00–21:00</strong><span>ежедневно</span></p></div></section>
    <section className="intro section-wrap" id="services" aria-labelledby="services-title"><div className="section-kicker"><span>01</span><p className="eyebrow">Всё в одном месте</p></div><div><h2 id="services-title">Красота по вашему сценарию</h2><p className="section-note">От быстрого маникюра до сложного окрашивания. Выбирайте услугу и удобное время в одном каталоге.</p></div></section>
    <section className="service-section section-wrap" aria-label="Основные услуги"><div className="service-grid">{services.map((service, index) => <article className={`service-item service-item-${index + 1}`} key={service.title}>{service.image && <img src={`${import.meta.env.BASE_URL}${service.image}`} alt={service.title} />}<div className="service-info"><span className="service-index">0{index + 1}</span><h3>{service.title}</h3><p>{service.detail}</p><strong>{service.price}</strong></div></article>)}</div></section>
    <section className="trust-section" id="reviews" aria-labelledby="reviews-title"><div className="trust-number"><span className="eyebrow">Нам доверяют</span><strong>{site.trust.rating}</strong><span className="stars">★★★★★</span><p>{site.trust.ratings} · {site.trust.reviews}</p></div><div className="trust-copy"><p className="eyebrow">02 / Отзывы гостей</p><h2 id="reviews-title">Тёплая атмосфера и мастера, к которым возвращаются</h2><div className="theme-list">{reviewThemes.map((theme) => <div key={theme.label}><strong>{theme.label}</strong><span>{theme.value}</span></div>)}</div><a className="text-link" href={`${site.mapUrl}reviews/`} target="_blank" rel="noreferrer">Читать отзывы <span aria-hidden="true">↗</span></a></div></section>
    <section className="prices-section section-wrap" id="prices" aria-labelledby="prices-title"><header className="section-header"><div><p className="eyebrow">03 / Выбор без сюрпризов</p><h2 id="prices-title">Популярные услуги</h2></div><p>Полный каталог насчитывает 104 услуги. Ниже — ориентиры для первого выбора.</p></header><div className="price-list">{prices.map(([title, price], index) => <div className="price-row" key={title}><span>0{index + 1}</span><h3>{title}</h3><strong>{price}</strong></div>)}</div><p className="price-note">Стоимость окрашивания и ухода зависит от длины волос. Актуальную цену уточняйте при записи.</p></section>
    <section className="contacts-section" id="contacts" aria-labelledby="contacts-title"><div className="contact-image"><img src={`${import.meta.env.BASE_URL}images/gallery-3.jpg`} alt="Деталь интерьера салона" /></div><div className="contact-copy"><p className="eyebrow">04 / До встречи</p><h2 id="contacts-title">Мокко во Владимире</h2><p className="address">{site.contact.address}</p><div className="contact-details"><div><span>График</span><strong>{site.contact.hours}</strong></div><div><span>Телефон</span><a href={site.contact.phoneHref}>{site.contact.phone}</a></div></div><div className="contact-actions"><a className="button button-accent" href={site.bookingUrl} target="_blank" rel="noreferrer">Записаться онлайн <span aria-hidden="true">↗</span></a><a className="button button-outline" href={site.routeUrl} target="_blank" rel="noreferrer">Построить маршрут <span aria-hidden="true">↗</span></a></div><div className="socials"><a href={site.contact.whatsapp} target="_blank" rel="noreferrer">WhatsApp</a><a href={site.contact.telegram} target="_blank" rel="noreferrer">Telegram</a><a href={site.contact.vk} target="_blank" rel="noreferrer">VK</a></div></div></section>
  </>
}
